# Generated by Django 5.0.8 on 2024-08-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=555)),
                ('tamanho', models.CharField(max_length=55)),
                ('preco', models.FloatField(default=0)),
                ('estoque', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=555)),
                ('ref', models.CharField(max_length=555)),
                ('custo', models.FloatField(default=0)),
                ('cadastro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=555)),
                ('tamanho', models.CharField(max_length=55)),
                ('preco', models.FloatField(default=0)),
                ('unidades', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=555)),
                ('ref', models.CharField(max_length=555)),
                ('custo', models.FloatField(default=0)),
                ('cadastro', models.DateTimeField()),
            ],
        ),
    ]
