# Generated by Django 5.0.8 on 2024-08-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=555)),
                ('cpf', models.CharField(max_length=20)),
                ('idt', models.CharField(max_length=30)),
                ('dn', models.DateField()),
                ('rua', models.CharField(max_length=555)),
                ('bairro', models.CharField(max_length=555)),
                ('numero', models.CharField(max_length=555)),
                ('cidade', models.CharField(max_length=555)),
                ('sapato', models.CharField(max_length=5)),
                ('roupa', models.CharField(max_length=5)),
                ('cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=20)),
                ('vencimento', models.DateField()),
                ('produto', models.CharField(max_length=555)),
                ('valor', models.FloatField()),
                ('cadastro', models.DateTimeField()),
            ],
        ),
    ]
