# Generated by Django 5.0.8 on 2024-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_notinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='forma',
            field=models.CharField(default='dinheiro', max_length=555),
        ),
    ]
