# Generated by Django 5.0.8 on 2024-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtovendido_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='notinha',
            name='status',
            field=models.CharField(default='aberto', max_length=555),
        ),
    ]
