# Generated by Django 5.0.8 on 2024-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notinha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovendido',
            name='vendedor',
            field=models.BigIntegerField(default=1),
        ),
    ]
