# Generated by Django 5.1.1 on 2024-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produtovendido_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(default='produto', max_length=555),
        ),
        migrations.AddField(
            model_name='produtovendido',
            name='produto',
            field=models.CharField(default='produto', max_length=555),
        ),
    ]
