# Generated by Django 5.1.1 on 2024-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_produto_produtovendido_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('nome_usuario', models.CharField(max_length=555)),
                ('cargo', models.CharField(max_length=55)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtovendido',
            name='descricao',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='produtovendido',
            name='loja',
            field=models.BooleanField(default=False),
        ),
    ]
