# Generated by Django 5.1.1 on 2024-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dadosuser_produto_descricao_produto_loja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.BigIntegerField()),
                ('nome_usuario', models.CharField(max_length=555)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
