# Generated by Django 5.1.1 on 2024-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.BigIntegerField(default=1),
        ),
    ]
