# Generated by Django 5.1.1 on 2024-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carrinho_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('id_produto', models.CharField(max_length=555)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
