# Generated by Django 5.1.1 on 2024-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fotoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notinha',
            name='cliente',
            field=models.CharField(max_length=555),
        ),
    ]
