# Generated by Django 5.1.1 on 2024-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notinha_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pedido',
            field=models.BooleanField(default=False),
        ),
    ]
