# Generated by Django 5.1.1 on 2024-11-20 17:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carrinho_enviado_carrinho_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cadastro',
            field=models.DateTimeField(default=core.models.Carrinho.hoje),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='contato',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='endereco',
            field=models.CharField(default='atualizar', max_length=999),
        ),
    ]
