# Generated by Django 5.1.1 on 2024-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carrinho_cadastro_carrinho_contato_carrinho_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.CharField(default='atualizar', max_length=555),
        ),
    ]
