# Generated by Django 5.1.1 on 2024-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carrinho_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cep',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cidade',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cpf',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='email',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='estado',
            field=models.CharField(default='atualizar', max_length=555),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='endereco',
            field=models.TextField(default='atualizar'),
        ),
    ]
