# Generated by Django 5.1.1 on 2024-12-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_carrinho_cep_carrinho_cidade_carrinho_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
