# Generated by Django 5.1.1 on 2025-03-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cliente_update_dadosuser_cadastro_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='produto',
        #     name='cor',
        #     field=models.CharField(default='#ffff', max_length=555),
        #     preserve_default=False,
        # ),
    ]
