# Generated by Django 5.1.1 on 2025-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sequencia',
            field=models.BigIntegerField(default=1),
        ),
    ]
