# Generated by Django 5.1.1 on 2025-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_produto_sequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=555)),
                ('aberto', models.BooleanField(default=True)),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCondicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicional', models.BigIntegerField()),
                ('produto', models.CharField(max_length=555)),
                ('cliente', models.CharField(max_length=555)),
                ('data_retirada', models.DateTimeField()),
                ('data_devolvido', models.DateTimeField(null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(default='', max_length=555),
            preserve_default=False,
        ),
    ]
