# Generated by Django 5.1.1 on 2025-09-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_condicionalcliente_produtocondicional_produto_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocondicional',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='produtocondicional',
            name='data_retirada',
        ),
    ]
