# Generated by Django 5.1.1 on 2025-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_produtocondicional_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocondicional',
            name='qtde',
            field=models.BigIntegerField(default=1),
        ),
    ]
